CRM-AGD/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM_AGD.Data;
using CRM_AGD.Models;

namespace CRM_AGD.Controllers
{
    public class CitiesController : Controller
    {
        private readonly CrmContext _context;

        public CitiesController(CrmContext context)
        {
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cities.ToListAsync());
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.Cities
                .SingleOrDefaultAsync(m => m.CityId == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CityId,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                _context.Add(city);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.Cities.SingleOrDefaultAsync(m => m.CityId == id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CityId,Name")] City city)
        {
            if (id != city.CityId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.CityId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.Cities
                .SingleOrDefaultAsync(m => m.CityId == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var city = await _context.Cities.SingleOrDefaultAsync(m => m.CityId == id);
            _context.Cities.Remove(city);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(int id)
        {
            return _context.Cities.Any(e => e.CityId == id);
        }
    }
}

CRM-AGD/Controllers/StreetPrefixesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM_AGD.Data;
using CRM_AGD.Models;

namespace CRM_AGD.Controllers
{
    public class StreetPrefixesController : Controller
    {
        private readonly CrmContext _context;

        public StreetPrefixesController(CrmContext context)
        {
            _context = context;
        }

        // GET: StreetPrefixes
        public async Task<IActionResult> Index()
        {
            return View(await _context.StreetPrefixes.ToListAsync());
        }

        // GET: StreetPrefixes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var streetPrefix = await _context.StreetPrefixes
                .SingleOrDefaultAsync(m => m.StreetPrefixId == id);
            if (streetPrefix == null)
            {
                return NotFound();
            }

            return View(streetPrefix);
        }

        // GET: StreetPrefixes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StreetPrefixes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Prefix,StreetPrefixId")] StreetPrefix streetPrefix)
        {
            if (ModelState.IsValid)
            {
                _context.Add(streetPrefix);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(streetPrefix);
        }

        // GET: StreetPrefixes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var streetPrefix = await _context.StreetPrefixes.SingleOrDefaultAsync(m => m.StreetPrefixId == id);
            if (streetPrefix == null)
            {
                return NotFound();
            }
            return View(streetPrefix);
        }

        // POST: StreetPrefixes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Prefix,StreetPrefixId")] StreetPrefix streetPrefix)
        {
            if (id != streetPrefix.StreetPrefixId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(streetPrefix);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StreetPrefixExists(streetPrefix.StreetPrefixId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(streetPrefix);
        }

        // GET: StreetPrefixes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var streetPrefix = await _context.StreetPrefixes
                .SingleOrDefaultAsync(m => m.StreetPrefixId == id);
            if (streetPrefix == null)
            {
                return NotFound();
            }

            return View(streetPrefix);
        }

        // POST: StreetPrefixes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var streetPrefix = await _context.StreetPrefixes.SingleOrDefaultAsync(m => m.StreetPrefixId == id);
            _context.StreetPrefixes.Remove(streetPrefix);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StreetPrefixExists(int id)
        {
            return _context.StreetPrefixes.Any(e => e.StreetPrefixId == id);
        }
    }
}

CRM-AGD/Controllers/StreetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM_AGD.Data;
using CRM_AGD.Models;

namespace CRM_AGD.Controllers
{
    public class StreetsController : Controller
    {
        private readonly CrmContext _context;

        public StreetsController(CrmContext context)
        {
            _context = context;
        }

        // GET: Streets
        public async Task<IActionResult> Index()
        {
            var crmContext = _context.Streets.Include(s => s.city).Include(s => s.streetPrefix);
            return View(await crmContext.ToListAsync());
        }

        // GET: Streets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var street = await _context.Streets
                .Include(s => s.city)
                .Include(s => s.streetPrefix)
                .SingleOrDefaultAsync(m => m.StreetId == id);
            if (street == null)
            {
                return NotFound();
            }

            return View(street);
        }

        // GET: Streets/Create
        public IActionResult Create()
        {
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "Name");
            ViewData["StreetPrefixId"] = new SelectList(_context.StreetPrefixes, "StreetPrefixId", "Prefix");
            return View();
        }

        // POST: Streets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StreetId,Name,CityId,StreetPrefixId")] Street street)
        {
            if (ModelState.IsValid)
            {
                _context.Add(street);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityId", street.CityId);
            ViewData["StreetPrefixId"] = new SelectList(_context.StreetPrefixes, "StreetPrefixId", "StreetPrefixId", street.StreetPrefixId);
            return View(street);
        }

        // GET: Streets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var street = await _context.Streets.SingleOrDefaultAsync(m => m.StreetId == id);
            if (street == null)
            {
                return NotFound();
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "Name", street.CityId);
            ViewData["StreetPrefixId"] = new SelectList(_context.StreetPrefixes, "StreetPrefixId", "Prefix", street.StreetPrefixId);
            return View(street);
        }

        // POST: Streets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StreetId,Name,CityId,StreetPrefixId")] Street street)
        {
            if (id != street.StreetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(street);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StreetExists(street.StreetId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityId", street.CityId);
            ViewData["StreetPrefixId"] = new SelectList(_context.StreetPrefixes, "StreetPrefixId", "StreetPrefixId", street.StreetPrefixId);
            return View(street);
        }

        // GET: Streets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var street = await _context.Streets
                .Include(s => s.city)
                .Include(s => s.streetPrefix)
                .SingleOrDefaultAsync(m => m.StreetId == id);
            if (street == null)
            {
                return NotFound();
            }

            return View(street);
        }

        // POST: Streets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var street = await _context.Streets.SingleOrDefaultAsync(m => m.StreetId == id);
            _context.Streets.Remove(street);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StreetExists(int id)
        {
            return _context.Streets.Any(e => e.StreetId == id);
        }
    }
}

CRM-AGD/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - CRM_AGD</title>

  <link href="~/Content/MvcLookup/mvc-lookup.css" rel="stylesheet">
  <link href="~/Content/MvcGrid/mvc-grid.css" rel="stylesheet">

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
  </environment>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CRM_AGD</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
          <li><a asp-area="Client" asp-controller="IssueFromPortals" asp-action="Create">Create issue</a></li>
          <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

          @if (SignInManager.IsSignedIn(User))
          {
            <li><a asp-area="" asp-controller="Home" asp-action="ChangeSubMenu" asp-route-module="@CRM_AGD.Enum.Module.Address">Address</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="ChangeSubMenu" asp-route-module="@CRM_AGD.Enum.Module.Equipment">Equipment</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="ChangeSubMenu" asp-route-module="@CRM_AGD.Enum.Module.Client">Client</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="ChangeSubMenu" asp-route-module="@CRM_AGD.Enum.Module.Mail">Mail</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="ChangeSubMenu" asp-route-module="@CRM_AGD.Enum.Module.Settlements">Settlements</a></li>
          }
        </ul>
        @await Html.PartialAsync("_LoginPartial")
      </div>
      @await Html.PartialAsync("_ModuleNavBar")
    </div>
  </nav>
  <div class="container body-content">
    @RenderBody()

    <script src="~/Scripts/JQuery/jquery-3.3.1.js"></script>

    <hr />
    <footer>
      <p>&copy; 2018 - CRM_AGD</p>
    </footer>
  </div>

  <environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  </environment>
  <environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
  </environment>

  @RenderSection("Scripts", required: false)
</body>
</html>

CRM-AGD/Views/Shared/_ModuleNavBar.cshtml
@using CRM_AGD

@{
  var checkModule = StaticValues.CheckModule;
}

@switch (checkModule)
{
  case (CRM_AGD.Enum.Module.Address):
    <ul class="nav navbar-nav">
      <li><a asp-area="Address" asp-controller="Cities" asp-action="Index">Cites</a></li>
      <li><a asp-area="Address" asp-controller="Streets" asp-action="Index">Streets</a></li>
      <li><a asp-area="Address" asp-controller="StreetPrefixes" asp-action="Index">Street Prefixes</a></li>
    </ul>
    break;
  case (CRM_AGD.Enum.Module.Equipment):
    <ul class="nav navbar-nav">
      <li><a asp-area="Equipment" asp-controller="Manufacturers" asp-action="Index">Manufacturer</a></li>
      <li><a asp-area="Equipment" asp-controller="MachineTypes" asp-action="Index">Machine Types</a></li>
      <li><a asp-area="Equipment" asp-controller="MachineModels" asp-action="Index">Models</a></li>
    </ul>
    break;
  case (CRM_AGD.Enum.Module.Client):
    <ul class="nav navbar-nav">
      <li><a asp-area="Client" asp-controller="Clients" asp-action="Index">Client</a></li>
      <li><a asp-area="Client" asp-controller="IssueFromPortals" asp-action="Index">Issue from portal</a></li>
      <li><a asp-area="Client" asp-controller="Issues" asp-action="Index">Issue</a></li>
    </ul>
    break;
  case (CRM_AGD.Enum.Module.Mail):
    <ul class="nav navbar-nav">
      <li><a asp-area="Mail" asp-controller="Inboxes" asp-action="Index">Inbox</a></li>
      <li><a asp-area="Mail" asp-controller="Sendboxes" asp-action="Index">Sendbox</a></li>
    </ul>
    break;
  case (CRM_AGD.Enum.Module.Settlements):
    <ul class="nav navbar-nav">
      <li><a asp-area="Settlements" asp-controller="Factures" asp-action="Index">Facture</a></li>
      <li><a asp-area="Settlements" asp-controller="VatRates" asp-action="Index">VAT rates</a></li>
    </ul>
    break;
}